version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: weather_app_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
      POSTGRES_DB: weather_app_db
    volumes:
      - postgres:/var/lib/postgresql/data

  weather_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres: